upstage-org/upstage

system/dev/event_resource_handler.nginx
user/templates/user/404.html
utils/formatting.py

systemd and nginx settings files, uwsgi files tested and running. 
app fixes while testing.

Issue 69 infra changes

---

dispatcher/__init__.py
run_upstage.py
ui/__init__.py

Closes #67 
This enhancement allows the entire UpStage system to be run as one
application despite UpStage being a collection of independent
subsystems.
It is not intended to be production-ready in its own right, but it does
make running the whole system easier while maintaining isolation of
subsystems while in development.
This change also creates a UI subsystem that is WSGI compliant while
also being a strictly client-side application.

Basic Orchestration

---

ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Dashboard.vue

user can see other user color in chat

Fix chat color of users

---

mqtt_server/Dockerfile
mqtt_server/README.md
mqtt_server/docker_build.sh
mqtt_server/docker_load.sh
mqtt_server/mosquitto.conf
mqtt_server/push_to_do.sh
mqtt_server/pw.txt

MQTT server build with our options, manual deployment of disk copy as an option.

mqtt server build, and optional manual deployment

---

config/settings/your_hostname.py
user/create_test_users.py

version bump in config

---

ui/dashboard/src/components/objects/ContextMenu.vue
ui/dashboard/src/views/live/Live.vue

Change Nickname from Context Menu

---

ui/dashboard/src/components/objects/ContextMenu.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/Skeleton.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/store/modules/stage.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/live/Live.vue
ui/dashboard/src/views/live/LoginPrompt.vue

Auto Dock Toolbox

---

ui/dashboard/package.json
ui/dashboard/src/App.vue
ui/dashboard/src/apollo.js
ui/dashboard/src/config.js
ui/dashboard/src/views/dashboard/StageManagement/Scenes.vue
ui/dashboard/yarn.lock

Setup GraphQL Client

---

ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/Topping.vue

Resolve #131 
- Avatar speech bubbles appear on top of all other avatars
- White background and black text on bubbles
- Wrap text if the line is too long. The max width of the bubble is based on the width of the avatar, but no smaller than 100px
- No bubble glitch on move/manipulating avatar

Speech Bubbles

---

user/schema.py

Trying to make a mutation throw me this error: 
`"errors": [
{
"message": "Schema is not configured for mutations"
}
],`
I guess it's because we're missing the mutation param inside graphene.Schema (like this: https://docs.graphene-python.org/en/latest/types/mutations/), hope this help!

User mutation in schema

---

requirements.pip
user/schema.py

Issue 137 cleanup gql 2

---

auth/auth_api.py
user/schema.py
utils/graphql_utils.py

Graphql update fixes, updated jwt conventions.

Issue 137 cleanup gql 3

---

user/schema.py

Graphql fixes/additions

---

ui/dashboard/src/components/form/EmojiInput.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/store/modules/stage/demoData.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/common.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/live/Live.vue

Audience Reaction

---

auth/auth_api.py
auth/auth_mutation.py
config/project_globals.py
requirements.pip
user/schema.py
user/user_api.py
utils/graphql_utils.py

Graphql access and refresh token handling, ability to query one user, and see db id.

Issue 137 cleanup gql 5

---

asset/sqlfiles/create.sql
auth/sqlfiles/create.sql
performance_config/sqlfiles/create.sql
ui/dashboard/.env.localhost
ui/dashboard/package.json
ui/dashboard/src/config.js

- Fix some sql syntax
- New script: `yarn serve:localhost` to start upstage front-end dev server with API point to localhost:5000

Setup Upstage Localhost

---

ui/dashboard/src/components/NavBar.vue
ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/styles/mixins.scss
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/dashboard/Layout.vue

1. Nav bar items should not shrink
2. Background image : it's better if it fit all web page
3. Hover the logo not put it with a box-shadow
4. The bubble in the chat : i think the box-shadow is heavy. Better to not put it here too
5. No box-shadow for the minux button or gears button on the chat
6. No box-shadow for context menu

Reduce box shadows

---

ui/dashboard/.eslintrc.js
ui/dashboard/package.json
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/store/modules/stage/demoData.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reactiveViewport.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/views/live/Live.vue
ui/dashboard/yarn.lock

Resolve #162 
Now users from different viewport will see the stage the same. But as a drawback, the stage must fit to a base ratio, for now I'm using 16/9, that ratio can be setting using the stage edit screen
Desktop:
Mobile:

Issue 162 Relative Size

---

ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/views/live/Live.vue

The context menu now recognise the existence of that chatbox 😅 
Resolve #163

Issue 163 Context Menu

---

ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reactiveViewport.js
ui/dashboard/src/store/modules/stage/reusable.js

Resize objects on stage resize

---

stage/asset.py
stage/schema.py
system/dev/upstage.nginx
ui/dashboard/package.json
ui/dashboard/src/App.vue
ui/dashboard/src/components/Asset.vue
ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/MediaUpload.vue
ui/dashboard/src/components/Modal.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrop.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/services/graphql/graphql.js
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/index.js
ui/dashboard/src/store/modules/auth.js
ui/dashboard/src/store/modules/cache.js
ui/dashboard/src/store/modules/user.js
ui/dashboard/src/views/dashboard/Media/MediaList.vue
ui/dashboard/src/views/dashboard/Media/index.vue
ui/dashboard/src/views/dashboard/StageManagement/General.vue
ui/dashboard/src/views/live/Live.vue
ui/dashboard/yarn.lock

- Filter asset type
- Audio upload
- Cache graphql result and static assets
- Loading cursor on router navigation

Media Upload Enhancement

---

stage/schema.py
ui/dashboard/src/components/MultiSelectList.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/demoData.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/store/modules/user.js
ui/dashboard/src/views/dashboard/Admin/index.vue
ui/dashboard/src/views/dashboard/Media/index.vue
ui/dashboard/src/views/dashboard/Profile/index.vue
ui/dashboard/src/views/dashboard/StageManagement/Chat.vue
ui/dashboard/src/views/dashboard/StageManagement/Layout.vue
ui/dashboard/src/views/dashboard/StageManagement/Media.vue
ui/dashboard/src/views/dashboard/StageManagement/index.vue
ui/dashboard/src/views/live/Layout.vue
ui/dashboard/src/views/live/PageLoader.vue

- Add/remove media to stage
- Load assigned media on playing the stage
- Namespace mqtt topics

Edit Stage Media 

---

stage/asset.py
stage/schema.py
system/dev/upstage.nginx
ui/dashboard/src/components/MultiSelectList.vue
ui/dashboard/src/components/form/Dropdown.vue
ui/dashboard/src/config.js
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/views/dashboard/Media/EditMedia.vue
ui/dashboard/src/views/dashboard/Media/MediaList.vue
ui/dashboard/src/views/dashboard/Media/index.vue
ui/dashboard/src/views/dashboard/StageManagement/Media.vue

Config updates

---

ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/SettingPopup/settings/Chat.vue
ui/dashboard/src/store/modules/stage/index.js

Since the relative position allowed us to use Ctrl + / Ctrl - of the navigator to scale the font of the chat
This PR allow us to set chat parameters as Elisa proposed, we can now Resolve #52

Chat Opacity Setting

---

ui/dashboard/src/components/objects/OpacitySlider.vue

Issue 191 slider

---

ui/dashboard/src/components/objects/Drawing.vue
ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/SavedDrawing.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/utils/canvas.js
ui/dashboard/src/utils/common.js

Part of #160 
https://user-images.githubusercontent.com/29925961/112748156-35a12200-8fe4-11eb-90e7-71d733398c23.mov

Live Action: Live Drawing

---

ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/store/modules/stage/index.js

Fix unstable caret issue when edit a saved text on stage

Fix Text Tool

---

auth/auth_api.py
auth/auth_mutation.py
stage/asset.py
stage/schema.py
ui/dashboard/src/components/DataTable/index.vue
ui/dashboard/src/views/dashboard/Media/MediaList.vue
user/schema.py
utils/graphql_utils.py

There was some issue when upload a media, the created_on got the value of 9 days ago, instead of the current date 🤔 After restarting the upstage service, the issue seems to be gone. But I figure it out, the backend was built with the main branch all the time (it should use the R1-2021). These changes need to be sync from main to R1-2021 to match the frontend params

Enhance GraphQL Connections

---

ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/live/PageLoader.vue

- Fix Live Stage url on homepage
- Fix stream url incorrect

Fix URL not found

---

auth/auth_api.py
ui/dashboard/src/App.vue
ui/dashboard/src/components/Confirm.vue
ui/dashboard/src/components/DataTable/index.vue
ui/dashboard/src/components/Modal.vue
ui/dashboard/src/components/form/MediaType.vue
ui/dashboard/src/components/form/RadioGroup.vue
ui/dashboard/src/components/form/SaveButton.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/services/rest/base.js
ui/dashboard/src/store/modules/user.js
ui/dashboard/src/utils/auth.js
ui/dashboard/src/utils/common.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Register.vue
ui/dashboard/src/views/dashboard/Admin/DeleteUser.vue
ui/dashboard/src/views/dashboard/Admin/RegistrationApproval.vue
ui/dashboard/src/views/dashboard/Admin/ResetPassword.vue
ui/dashboard/src/views/dashboard/Admin/SwitchRole.vue
ui/dashboard/src/views/dashboard/Admin/UserTable.vue
ui/dashboard/src/views/dashboard/Admin/index.vue
user/schema.py

Resole #199:
- Sort users by: username, email, registration date, role, status
- Reset password of other user
- Change role of other user
- Delete a user

Issue 199 User Management

---

ui/dashboard/src/components/form/ElasticInput.vue
ui/dashboard/src/components/form/EmojiInput.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/views/live/Live.vue

Issue 212 Chat Box

---

ui/dashboard/src/components/DataTable/index.vue
ui/dashboard/src/components/form/Switch.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/utils/auth.js
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/dashboard/Dashboard.vue
ui/dashboard/src/views/dashboard/Layout.vue
ui/dashboard/src/views/dashboard/Media/index.vue

Merge the My Stage menu with Dashboard, with the help of owner filter:

Issue 206 My Stages

---

ui/dashboard/src/components/objects/Avatar/index.vue
ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 221 Objects Positioning

---

asset/models.py
group/models.py
license/models.py
performance_config/models.py

Issue 207 Wrong Upload Date

---

ui/dashboard/src/components/Popover.vue
ui/dashboard/src/components/stage/ConnectionStatus.vue
ui/dashboard/src/components/stage/SettingPopup/settings/Chat.vue
ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/user.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/live/ConnectionStatus.vue
ui/dashboard/src/views/live/Live.vue
ui/dashboard/src/views/live/LoginPrompt.vue
ui/dashboard/src/views/live/Session.vue

Player/Audience Counter

---

auth/auth_api.py
ui/dashboard/src/components/MediaUpload.vue
ui/dashboard/src/components/ProfileForm.vue
ui/dashboard/src/components/form/Upload.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/dashboard/Admin/UploadLimit.vue
ui/dashboard/src/views/dashboard/Admin/index.vue
ui/dashboard/src/views/dashboard/Media/MediaList.vue
user/models.py
user/schema.py
user/sqlfiles/create.sql

- Prevent upload file lagger than 1Mb
- New Admin section: Upload Limit, admin can override user's upload limit up to 100Mb
- Add column `upload_limit` to `upstage_user` table and drop `phone`, `ok_to_sms column` from `upstage_user`

Issue 218 Upload Limit

---

ui/dashboard/public/icons/maximize.svg
ui/dashboard/public/icons/pause.svg
ui/dashboard/public/icons/scene.svg
ui/dashboard/public/icons/stage.svg
ui/dashboard/src/components/MediaUpload.vue
ui/dashboard/src/components/form/Upload.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue

- Upload limit visible to user
- Unlimit video upload size
- File extension filter based on media type
- New icons by Riad

UI/UX Enhancement

---

ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/store/modules/stage/index.js

Fix Impact Bugs

---

ui/dashboard/package.json
ui/dashboard/src/components/LoginForm.vue
ui/dashboard/src/components/TermsOfService.vue
ui/dashboard/src/views/Login.vue
ui/dashboard/src/views/Register.vue
ui/dashboard/yarn.lock

I'm using the `README.md` inside `documentation` repo as a placeholder. This will change as soon as we finish the Terms

Terms of Service

---

ui/dashboard/package.json
ui/dashboard/src/components/Footer.vue

Issue 31 Footer

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Avatar/index.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/store/modules/stage/index.js

Slider mode is now different for each avatar and player
Resolves #150

Issue 150 Slider Mode

---

ui/dashboard/src/store/modules/stage/index.js

Issue 251 Repeated Message

---

ui/dashboard/src/components/form/EmojiInput.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/dashboard/Dashboard.vue
ui/dashboard/src/views/dashboard/StageManagement/index.vue

Issue 235 Abandoned Avatar

---

ui/dashboard/src/components/form/Upload.vue
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/dashboard/Admin/UploadLimit.vue

Change upload hint proposed as Helen

Change Upload Hint

---

ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/services/graphql/graphql.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/user.js

- Audience now don't see the spinning icon above avatar
- Fix refresh token loop issue when refresh token is expire

Issue 247 Audience View

---

.github/workflows/app1.yml
README.md

Auto ssh to app1 machine and build the latest code when pull request to R1-2021 got approved

Setup GitHub Action for app1

---

ui/dashboard/src/components/objects/Topping.vue

Sorry I forgot about the bubble 😅 
Resolve #39

Link inside chat bubble

---

stage/schema.py
ui/dashboard/src/components/MultiSelectList.vue
ui/dashboard/src/components/objects/Drawing.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/views/dashboard/StageManagement/Media.vue
ui/dashboard/src/views/dashboard/StageManagement/SweepStage.vue

Issue 160 Live Action

---

.github/workflows/devapp1.yml
event_archive/config.py
run_event_archive.py
run_upstage.py
system/dev/event_archive.service

Since starting `event archive` in UpStage's subprocess cause duplicated events got inserted into Postgres, this PR will fix it

Event Archive as separated service

---

ui/dashboard/src/components/NavBar.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Setting.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/live/Live.vue

New toolbox - Setting that able to:
- Hide chat in live performance, Resolves #290 
- Set backdrop fallback color, Resolve #209

Issue 290 Setting Tools

---

ui/dashboard/src/components/objects/Moveable.vue

Issue 275 Resize Objects

---

ui/dashboard/src/components/form/Upload.vue

Issue 298 Media format

---

ui/dashboard/src/components/form/InputButtonPostfix.vue
ui/dashboard/src/views/live/LoginPrompt.vue

Issue 258 Prompt on Enter Stage

---

ui/dashboard/src/components/form/InputButtonPostfix.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/dashboard/StageManagement/Records.vue
ui/dashboard/src/views/live/LoginPrompt.vue

Issue 258 Enter stage (cont)

---

.github/workflows/app1.yml
.github/workflows/devapp1.yml
ui/dashboard/src/views/Login.vue

Hot fix login redirect (C3PO)

---

.github/workflows/app1.yml
.github/workflows/devapp1.yml
ui/dashboard/src/views/Login.vue

Hot fix login redirect

---

asset/models.py
stage/asset.py
stage/schema.py
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/utils/stage.js
ui/dashboard/src/views/backstage/Media/EditMedia.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/backstage/Stages.vue
user/schema.py

Stages and media delete button

Issue 35 Media Deletion

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/live/Layout.vue
ui/dashboard/src/views/live/Preloader.vue

Trick the user to click in order to play meSpeak voice

Issue 57 Artificial Click

---

stage/asset.py
ui/dashboard/src/components/Asset.vue
ui/dashboard/src/components/Modal.vue
ui/dashboard/src/components/MultiSelectList.vue
ui/dashboard/src/components/Tabs.vue
ui/dashboard/src/components/form/Field.vue
ui/dashboard/src/components/form/MediaType.vue
ui/dashboard/src/views/backstage/Media/MediaEdit.vue
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/Media/MediaUpload.vue
ui/dashboard/src/views/backstage/Media/index.vue

Issue 347 Upload Flow

---

stage/asset.py
ui/dashboard/src/components/Asset.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/StageManagement/Media.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue

Resolves #348 and minor UI changes

Issue 348 Success Message

---

ui/dashboard/src/components/Modal.vue
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/backstage/Media/MediaUpload.vue
ui/dashboard/src/views/backstage/Media/index.vue

Issue 339 Different Backdrop

---

ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/live/Layout.vue
ui/dashboard/src/views/live/Preloader.vue

Issue 341 Speech Bubble

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/live/LoginPrompt.vue

- Adjust move speed ranges
- Reload stage permission after login prompt

Issue 293 Move Speed

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue

Issue 350 Opacity Fading

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js

Issue 351 Light Bulb

---

system/prod/build_streaming1_nginx.sh
system/prod/streaming1_nginx.conf

Streaming config for production server.

streaming without recording, no file I/O, all memory-resident

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Avatar/index.vue
ui/dashboard/src/components/objects/Drawing.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Avatars.vue
ui/dashboard/src/components/stage/Toolbox/tools/Depth.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/SavedDrawing.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Props.vue
ui/dashboard/src/components/stage/Toolbox/tools/Stream/Webcam.vue
ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/live/Layout.vue

Resolves #58:
- New Depth tools:
- Avatar not brought to front when speaking anymore

Issue 58 Props

---

ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/store/modules/user.js

Resolves #385 
- Not persist nick name after change it during performance
- Show sliders on props

Issue 385 Nickname

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrop.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/backstage/Media/MultiframePreview.vue

Issue 279 Multiframe Backdrops

---

ui/dashboard/src/services/speech/index.js
ui/dashboard/src/views/backstage/Media/MultiframePreview.vue

Issue 369 Unstable Voices

---

ui/dashboard/public/icons/animation-slider.svg
ui/dashboard/public/icons/movement-slider.svg
ui/dashboard/public/icons/opacity-slider.svg
ui/dashboard/public/icons/remove.svg
ui/dashboard/public/icons/voice-setting-invert.svg
ui/dashboard/public/icons/voice-setting.svg
ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/stage/SettingPopup/settings/VoiceParameters.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue

Issue 260 Context Menu Enhancements

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/live/ConnectionStatus.vue

Issue 352 Re-positioning things in depth

---

ui/dashboard/src/services/speech/index.js

Issue 337 Voice and Emoji

---

ui/dashboard/src/assets/shout.svg
ui/dashboard/src/assets/speak.svg
ui/dashboard/src/assets/think.svg
ui/dashboard/src/components/form/ChatInput.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/SettingPopup/settings/ChatBox.vue
ui/dashboard/src/services/speech/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/styles/speech.scss

Issue 355 Thinking Shouting

---

stage/schema.py
ui/dashboard/src/App.vue
ui/dashboard/src/components/Modal.vue
ui/dashboard/src/components/NavBar.vue
ui/dashboard/src/components/Skeleton.vue
ui/dashboard/src/components/form/ImagePicker.vue
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/cache.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/user.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/Media/MediaUpload.vue
ui/dashboard/src/views/backstage/Media/index.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue
ui/dashboard/src/views/backstage/Stages.vue
ui/dashboard/src/views/live/Preloader.vue

Sorry I promised to do this a long time ago but I forget, primarily because we don't have a Github issue for this, we just discussed about it on Slack 😅
Pick a cover image in Stage Management, and your stage's loading screen will look like this 🎉:

Stage cover image

---

ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/SettingPopup/settings/ChatParameters.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 51 Chat font size

---

ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/speech.scss
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/backstage/StageManagement/Layout.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue

We can now choose the animation of the speech bubble in Stage Management. Resolves #355

Issue 355 Speech bubble animation

---

ui/dashboard/src/components/form/ImagePicker.vue
ui/dashboard/src/components/stage/AudioPlayer.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/store/modules/stage/index.js

Resolves #30: audio seeker, loop toggle and adjust volume

Issue 30 Audio Tool

---

system/dev/dev_app1_nginx_upstage.conf
system/prod/app1_nginx_upstage.conf

Vanity URLs

---

event_archive/actions.py
ui/dashboard/src/components/stage/PlayerAudienceCounter.vue
ui/dashboard/src/components/stage/StageTable.vue
ui/dashboard/src/components/stage/composable.js
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/Stages.vue
ui/dashboard/src/views/live/ConnectionStatus.vue

Issue 29 Player and Audience counter

---

ui/dashboard/src/components/form/ChatInput.vue
ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 34 Chat Styling

---

ui/dashboard/src/components/Asset.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue

Issue 416 Square frames

---

ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/views/backstage/StageManagement/Customization.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue

Issue 418 Auto detect live streams option

---

ui/dashboard/src/styles/custom.scss

Issue 428 Custom scrollbar

---

ui/dashboard/src/assets/shout.svg
ui/dashboard/src/assets/think.svg
ui/dashboard/src/components/form/ElasticInput.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/AudioPlayer.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/speech.scss

Issue 355 Speech bubbles enhancement

---

ui/dashboard/public/icons/loop.svg
ui/dashboard/public/icons/toggle_off.svg
ui/dashboard/public/icons/toggle_on.svg
ui/dashboard/src/components/Icon.vue
ui/dashboard/src/components/form/Switch.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/speech.scss
ui/dashboard/src/views/backstage/StageManagement/General.vue
ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue

Issue 427 Resizing frame & save button

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 388 Costume prop

---

config/schema.py
config/settings/__init__.py
ui/dashboard/src/components/MultiTransferColumn.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue

Issue 377 Finding players

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/components/stage/Toolbox/tools/Setting.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue

Issue 372 Clear Chat

---

ui/dashboard/src/components/Tabs.vue
ui/dashboard/src/views/backstage/StageManagement/Chat.vue
ui/dashboard/src/views/backstage/StageManagement/ClearChat.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue
ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue

Have the chat separated into sessions, by date/time and export them to txt files. Resolves #245

Issue 245 Chat Management

---

ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/backstage/Media/MediaList.vue

Re position speech bubbles when it hit the walls (#355)

Issue 355 Speech bubbles (cont)

---

ui/dashboard/src/store/modules/stage/index.js

Issue 388 Costume Rotation

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/store/modules/stage/index.js

Resolves #444 
And re implement costume rotating (#388)

Issue 444 Last speech

---

ui/dashboard/src/components/form/MediaType.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Curtain.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/speech.scss
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue

Issue 244 Stage Curtain

---

ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/SettingPopup/index.vue
ui/dashboard/src/components/stage/SettingPopup/settings/SaveScene.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scene/Scene.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scene/index.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js

Issue 456 Audience Frames

---

ui/dashboard/src/services/speech/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/replay/Controls.vue

- Not restart the replay from the begin after changing speed
- Fix sound has to "catch-up" if rewinding manually
- Fix speed not taking effects

Fix performance replaying bugs

---

ui/dashboard/src/components/form/Switch.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Curtain.vue
ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/StageManagement/Customization.vue

Issue 370 Curtain animation

---

ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/styles/mixins.scss

Issue 421 Differentiated toolbar

---

ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/views/live/LoginPrompt.vue

Issue 459 Nickname prompt & Stream identification

---

ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/styles/speech.scss
ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue

Issue 468 Different media

---

stage/schema.py
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js

Leaving the stage in an inactive tab for a while will make the mqtt client closes the connection. After reconnecting all speeches got re-spoken again (#455). These changes will fix it

Issue 455 Reconnect Handling

---

ui/dashboard/src/components/stage/AudioPlayer.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/store/modules/stage/reusable.js

Issue 30 Playing audio with hotkeys

---

ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/live/LoginPrompt.vue

Issue 473 Backdrop Colour

---

ui/dashboard/src/components/form/ElasticInput.vue
ui/dashboard/src/components/stage/Chat/PlayerChat.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/SettingPopup/settings/ChatBox.vue
ui/dashboard/src/components/stage/Toolbox/PlayerChat.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/live/Layout.vue
ui/dashboard/src/views/live/Session.vue

Players now have a separated chat box, which is hidden from audience. The box can be minimised to toolbox, and auto pop out when some one mention them (using the @ + nickname). The chat box can also be moved and resized 👌 Resolves #32

Issue 32 Private Communication

---

ui/dashboard/src/components/objects/Drawing.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/SavedDrawing.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js

After this we can roll 6-5C to app1 🙌

Fix saving drawing/text issue

---

ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/styles/custom.scss

Issue 220 Text tool improvement

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/store/modules/stage/index.js

Resolves #467 
And improve resizing frames positions during animation

Issue 467 Mute stream locally

---

ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Topping.vue
ui/dashboard/src/components/stage/Curtain.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/backstage/StageManagement/Customisation.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue
ui/dashboard/src/views/live/Preloader.vue

Issue 431 Cover image proportions

---

ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrop.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 259 Backdrop Opacity

---

ui/dashboard/package.json
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/views/live/LoginPrompt.vue

Issue 467 Mute stream option

---

ui/dashboard/src/components/objects/Streamer/index.vue

Issue 485 Cleanup orphaned streams

---

ui/dashboard/src/components/stage/Toolbox/PanelItem.vue
ui/dashboard/src/components/stage/Toolbox/index.vue

Issue 495 Toolbox

---

asset/models.py
licenses/models.py
licenses/sqlfiles/create.sql
stage/asset.py
stage/schema.py
ui/dashboard/src/components/form/ChatInput.vue
ui/dashboard/src/components/form/Dropdown.vue
ui/dashboard/src/components/form/MediaType.vue
ui/dashboard/src/components/form/Upload.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/Media/MediaList.vue
ui/dashboard/src/views/backstage/Media/MediaUpload.vue

Allow player to replace a media that already uploaded (#35) and set media copyright (#7)

Issue 7 Media copyright

---

ui/dashboard/src/components/DataTable/Pagination.vue
ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/Toolbox/PanelItem.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/views/backstage/Media/MediaForm.vue

Resolves #503, and minor UI fixes/improvements required to resovles #7

Issue 503 Message mouse hover

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Drawing.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/store/modules/stage/index.js

Delete drawing permanently and save drawing as Avatar or Prop. Resovles #505

Issue 505 Drawing Object Tool

---

ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Whiteboard.vue
ui/dashboard/src/components/stage/Whiteboard.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/utils/constants.js

New "Live drawing" tool, which allows direct screen drawing like BBB Whiteboard 🙌 
https://user-images.githubusercontent.com/29925961/128591838-95b6b7bd-2b1d-463b-8baa-3761d8079860.mp4

Issue 507 Live drawing

---

ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/components/stage/composable.js
ui/dashboard/src/router/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/replay/Controls.vue
ui/dashboard/src/views/replay/EventIndicator.vue

Events indicator and action seek, toggle replay controls visibility (#53)

Issue 53 Recording Enhancement

---

ui/dashboard/src/components/DataTable/index.vue
ui/dashboard/src/components/form/Switch.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/views/backstage/Admin/DeleteUser.vue
ui/dashboard/src/views/backstage/Admin/ProfileManagement.vue
ui/dashboard/src/views/backstage/Admin/RegistrationApproval.vue
ui/dashboard/src/views/backstage/Admin/ResetPassword.vue
ui/dashboard/src/views/backstage/Admin/SwitchRole.vue
ui/dashboard/src/views/backstage/Admin/UploadLimit.vue
ui/dashboard/src/views/backstage/Admin/UserTable.vue
ui/dashboard/src/views/backstage/Admin/index.vue

Issue 375 Player management

---

ui/dashboard/package.json
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Curtain.vue
ui/dashboard/src/components/stage/SettingPopup/settings/ChatParameters.vue
ui/dashboard/src/components/stage/Whiteboard.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/yarn.lock

This PR will fix these 2 issues happened during our meeting last night:
- The right curtain stuck 😅 
- The drawn square not positioned around Helen avatar on narrower viewport

Fix Curtain and Live Drawing

---

ui/dashboard/src/components/Modal.vue
ui/dashboard/src/components/stage/AudioPlayer.vue
ui/dashboard/src/components/stage/RecordActions.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/components/stage/composable.js
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue
ui/dashboard/src/views/replay/Controls.vue

Issue 53 Replay Recordings

---

config/settings/your_hostname.py
stage/asset.py
stage/schema.py
ui/dashboard/package.json
ui/dashboard/src/components/Asset.vue
ui/dashboard/src/components/LarixQRCode.vue
ui/dashboard/src/components/QRCode.vue
ui/dashboard/src/components/stage/Toolbox/tools/Streams/QRCodePopup.vue
ui/dashboard/src/components/stage/Toolbox/tools/Streams/index.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/utils/streaming.js
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/Media/MediaUpload.vue
ui/dashboard/src/views/backstage/Media/OBSInstruction.vue
ui/dashboard/src/views/backstage/Media/StreamPreview.vue
ui/dashboard/yarn.lock

Issue 493 Streaming Security

---

ui/dashboard/src/components/form/Dropdown.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/components/objects/Text.vue
ui/dashboard/src/components/stage/Curtain.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue

We now have 2 modes for text: "editing" and "moving". Click that button to toggle between these modes 🙌

Editing mode and Text tool improvements

---

ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue

Because this is a hotfix, I target it to the `main` branch so that it could be deployed into app1
Resolves #537

Issue 530 Font Dropdown

---

ui/dashboard/src/components/stage/Chat/Reaction.vue
ui/dashboard/src/components/stage/Toolbox/tools/Settings.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/utils/constants.js

Issue 548 Reactions toggle setting

---

stage/asset.py
ui/dashboard/src/views/backstage/Layout.vue

Hot fix issues #531 and #541

---

ui/dashboard/src/views/backstage/Media/MultiframePreview.vue
ui/dashboard/src/views/backstage/StageManagement/Media.vue

Issue 524 Multiframe Identification

---

ui/dashboard/src/components/form/ChatInput.vue
ui/dashboard/src/components/stage/composable.js

Issue 529 Emoji single/multiple picker mode

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 535 Consistence text drawing

---

ui/dashboard/src/components/form/ChatInput.vue
ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Moveable.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue

Resolves #56 
And hot fix #553 as well

Issue 56 Flip operation

---

ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/store/modules/stage/index.js

Issue 40 Remove and highlight messages

---

ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/Admin/BatchUserCreation.vue
ui/dashboard/src/views/backstage/Media/MediaForm.vue
ui/dashboard/src/views/backstage/StageManagement/Media.vue

Curtain are now must be assigned to a stage to be used, and are shown in the media management section of the stage. Resolves #546

Issue 546 - Assignable curtain

---

ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/objects/OpacitySlider.vue
ui/dashboard/src/components/objects/QuickAction.vue
ui/dashboard/src/components/stage/Chat/PlayerChat.vue
ui/dashboard/src/views/backstage/Media/MediaForm.vue

Issue 545 Clickable link on stage

---

.github/workflows/devapp1.yml
ui/dashboard/package.json
ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/services/graphql/graphql.js
ui/dashboard/src/views/live/Layout.vue
ui/dashboard/src/views/live/Preloader.vue

Resolves #476, and hot fix #560

Issue 476 Stage statuses

---

ui/dashboard/src/components/objects/Streamer/index.vue

Hey, can you check my pull request
Resolves #542

Issue 542 Mute 4 all streams

---

system/dev/dev_app1_nginx_upstage.conf
system/prod/app1_nginx_upstage.conf
ui/dashboard/.env.dev
ui/dashboard/package.json
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/utils/common.js
ui/dashboard/src/views/live/FirefoxWarning.vue
ui/dashboard/src/views/replay/Controls.vue

Resolves #30, and fix Firefox about:config trick not showing (#565)

Issue 30 Audio player layout

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Settings.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/components/stage/Toolbox/tools/Whiteboard.vue
ui/dashboard/src/views/live/FirefoxWarning.vue

Resolves #569
Part of #484 and #565

Issue 569 Typo, British Spelling and Firefox warning

---

ui/dashboard/src/components/Image.vue
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/utils/constants.js

Issue 578 Multi-frame fade transition

---

ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/views/backstage/StageManagement/Customisation.vue
ui/dashboard/src/views/live/FirefoxWarning.vue

Issue 574 Curtain settings and Firefox instruction wording

---

ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/views/backstage/StageManagement/Customisation.vue

Resolves #577 
And adjust the lowest speed of curtain transition to 5s, resolves #574

Issue 577 Chat box enhancement

---

ui/dashboard/package.json
ui/dashboard/src/components/stage/Chat/PlayerChat.vue
ui/dashboard/src/components/stage/Chat/index.vue

Issue 584 Minimise player chat

---

.github/workflows/devapp1.yml
ui/dashboard/src/views/backstage/StageManagement/Archive.vue

Issue 586 Replay navigation

---

ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrops.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/styles/custom.scss
ui/dashboard/src/views/live/FirefoxWarning.vue
ui/dashboard/src/views/live/Preloader.vue

Issue 593 Multiframe backdrop

---

ui/dashboard/src/views/live/Preloader.vue

Issue 601 Loading screen message

---

ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/StageManagement/Archive.vue
ui/dashboard/src/views/backstage/StageManagement/Media.vue
ui/dashboard/src/views/live/FirefoxWarning.vue

Issue 586 Recording navigation

---

ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue

Hotfix issue #673 and fix typo in #672 😅

Hotfix 673 Blank create stage

---

.github/workflows/app1.yml
system/prod/app1_nginx_upstage.conf
ui/dashboard/.env
ui/dashboard/package.json
ui/dashboard/src/components/Popover.vue
ui/dashboard/src/components/stage/PlayerAudienceCounter.vue
ui/dashboard/src/components/stage/Toolbox/tools/Settings.vue
ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue
ui/dashboard/src/views/live/ConnectionStatus.vue
ui/studio/.env.dev
ui/studio/.env.production
ui/studio/src/config.ts
ui/studio/src/utils/common.ts

Resolve #664, #663, #672 and #646

Statistics and Wordings Enhancements

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue

Issue 568 Animation slider and volume slider

---

ui/dashboard/src/components/Image.vue
ui/dashboard/src/components/stage/Backdrop.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrops.vue

Issue 593 Multiframe backdrop animation

---

ui/dashboard/src/store/modules/stage/index.js

Issue 689 Backdrop disappearing

---

ui/dashboard/src/store/modules/stage/index.js

I cherry-picked the last commit and create this pull request to `main` branch so that the bug got fixed on `upstage.live`!

Issue 689 Backdrop disappearing (to main)

---

asset/models.py
asset/sqlfiles/create.sql
licenses/models.py
licenses/sqlfiles/create.sql
studio/media.py
studio/notification.py
studio/schema.py
ui/dashboard/package.json
ui/studio/src/components/display/DName.vue
ui/studio/src/components/media/MediaFilter.vue
ui/studio/src/components/media/MediaForm/MediaPermissions.vue
ui/studio/src/components/media/MediaForm/RequestAcknowledge.vue
ui/studio/src/components/media/MediaForm/RequestPermission.vue
ui/studio/src/components/media/MediaForm/composable.ts
ui/studio/src/components/media/MediaForm/index.vue
ui/studio/src/components/media/MediaTable.vue
ui/studio/src/components/media/Notifications.vue
ui/studio/src/components/upstage/SmartButton.vue
ui/studio/src/config.ts
ui/studio/src/models/fragment.ts
ui/studio/src/models/studio.ts

Media permissions and notifications system. Resolves #547

Upstage Studio V1.3

---

README.md

Add links to the new documentation website

Update README.md to Include Documentation

---

ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Settings.vue
ui/dashboard/src/services/mqtt/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js
ui/dashboard/src/utils/constants.js

Issue 708 Dark mode chat

---

auth/auth_api.py
studio/media.py
ui/dashboard/src/utils/constants.js
user/models.py

Issue 677 Remove unnecessary roles

---

auth/auth_api.py
studio/media.py
ui/dashboard/src/utils/constants.js
user/models.py

This is just a cherry-pick pull request to `main` branch so that this issue can be resolved on `upstage.live` and `meta` instance!

Issue 677 Remove unnecessary roles (for meta and live)

---

studio/media.py
studio/schema.py
ui/dashboard/src/components/stage/SettingPopup/settings/VoiceParameters.vue
ui/dashboard/src/router/index.js
ui/dashboard/src/services/speech/index.js
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/Layout.vue
ui/studio/index.html
ui/studio/public/js/mespeak
ui/studio/src/components/media/MediaForm/AvatarVoice.vue
ui/studio/src/components/media/MediaForm/VoicePicker.vue
ui/studio/src/components/media/MediaForm/composable.ts
ui/studio/src/components/media/MediaForm/index.vue
ui/studio/src/components/media/MediaPreview.vue
ui/studio/src/models/studio.ts
ui/studio/src/services/speech/index.ts
ui/studio/src/services/speech/voice.ts

- Replicate voice from another avatar. Resolves #426 
- No voice option. Resolves #645 
- Take the voice function away from streams completely. Resolves #714 
- Shut down the old Media Management section (all the feature has already implemented in Studio)

UpStage Studio V1.4

---

ui/dashboard/package.json
ui/dashboard/src/components/Footer.vue
ui/studio/src/components/media/MediaForm/index.vue

Issue 722 Tiny Typo

---

ui/dashboard/package.json
ui/dashboard/src/components/Footer.vue
ui/studio/src/components/media/MediaForm/index.vue

I cherry pick the previous commit to main branch so that it got released in `meta` and `live` instance.

Update meta and live footer

---

ui/dashboard/src/views/backstage/Layout.vue
ui/dashboard/src/views/live/Layout.vue
ui/studio/src/components/media/MediaFilter.vue

- Navigations from live stage to back stage. Resolves #679 
- Navigations from studio to Foyer. Load studio in the same tab from Backstage Resolves #723

Issue 723 & 679 Navigations

---

auth/auth_mutation.py
mail/mail_utils.py
ui/dashboard/.env.localhost
ui/dashboard/src/components/LoginForm.vue
ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/services/graphql/user.js
user/models.py
user/schema.py
user/totp.py

Issue 731 Forgot password

---

ui/dashboard/src/components/ProfileForm.vue
ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue
user/models.py
user/schema.py
user/sqlfiles/create.sql

Issue 615 Agreed to terms

---

ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js

Issue 739 Round Eraser

---

ui/dashboard/src/components/Logo.vue
ui/dashboard/src/views/live/Layout.vue

Issue 742 Leave stage menu

---

ui/dashboard/src/components/stage/Backdrop.vue

Issue 749 Backdrop proportions

---

auth/auth_mutation.py
mail/mail_utils.py
mail/templates.py
user/schema.py

Issue 756 Managing registrations

---

ui/dashboard/src/components/stage/Toolbox/tools/Backdrops.vue

Issue 748 Backdrop thumbnail tooltip

---

ui/dashboard/src/components/Modal.vue
ui/dashboard/src/views/backstage/Admin/UserTable.vue

Issue 695 & 766 Scrollbar and player table

---

ui/studio/src/components/media/MediaForm/AvatarVoice.vue
ui/studio/src/components/media/MediaPreview.vue
ui/studio/src/services/speech/voice.ts
ui/studio/vite.config.ts

Resolves #645 
And continue of #720

Issue 645 No voice option

---

studio/media.py
studio/schema.py
user/schema.py

Issue 768 Unassigning media

---

ui/dashboard/yarn.lock

Sync lib changes in main to the current branch.

Sync library updates to release branch

---

studio/media.py
studio/schema.py
ui/studio/src/components/media/MediaFilter.vue
ui/studio/src/components/media/MediaTable.vue
ui/studio/src/components/media/QuickStageAssignment.vue
ui/studio/src/config.ts
ui/studio/src/models/studio.ts

Issue 787 Non author permission in Studio

---

ui/dashboard/src/components/stage/Chat/index.vue

Issue 625 New chat indicator

---

ui/dashboard/src/store/modules/auth.js
ui/studio/src/components/media/MediaFilter.vue
ui/studio/src/models/config.ts

Issue 785 Default studio view

---

ui/dashboard/.env.live
ui/dashboard/.env.meta
ui/dashboard/src/components/stage/Chat/index.vue

Issue 625 Dark mode indicator

---

config/schema.py
ui/dashboard/src/services/graphql/config.js
ui/dashboard/src/store/modules/config.js
ui/dashboard/src/views/backstage/Admin/SystemConfigurations.vue
ui/dashboard/src/views/backstage/Layout.vue

Issue 786 Manual link from backstage

---

ui/dashboard/package.json
ui/dashboard/src/components/form/ColorPicker.vue
ui/dashboard/src/components/stage/Board.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/components/stage/Toolbox/TopBar.vue
ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
ui/dashboard/src/components/stage/Toolbox/tools/Backdrops.vue
ui/dashboard/src/components/stage/Toolbox/tools/Curtain.vue
ui/dashboard/src/components/stage/Toolbox/tools/Meeting/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scenes/Scene.vue
ui/dashboard/src/components/stage/Toolbox/tools/Streams/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/Home.vue
ui/dashboard/yarn.lock

Issue #796 consists of 2 parts: on stage reordering and backstage reordering. This pull request will allow toolbar items to be reordered by drag and drop, the other will be coming soon!

Issue 796 Reorder toolbar overlay (Part 1 - On stage)

---

config/settings/__init__.py

Crash logger needed a variable for devs which should receive emails.

small fix for crash emails

---

run_script.py
scripts/wipe_dev.py
system/dev/scripts/terminal_colors.py
system/dev/scripts/wipe_dev.py

To run it: `python3 run_script.py wipe_dev`

The script for cleaning up dev instance 

---

ui/dashboard/src/components/LoginForm.vue
ui/dashboard/src/components/form/Field.vue

Issue 813 Strip spaces

---

ui/dashboard/src/views/backstage/Admin/UserTable.vue

Issue 833 Empty player table

---

ui/studio/src/components/media/MediaForm/index.vue

Issue 829 Fix uploaded audio & video not changing source

---

user/schema.py

Issue 817 Delete stage when deleting stage's owner

---

ui/dashboard/src/components/stage/DeleteStage.vue

Issue 479 Delete stage question

---

ui/dashboard/package.json
ui/dashboard/yarn.lock

Upgrade ansi-html to 0.0.8

---

ui/studio/src/components/media/MediaForm/StageAssignment.vue
ui/studio/src/components/media/MediaForm/index.vue

Issue 861 Fix upload new media overwrite the last edited one

---

system/dev/scripts/scaffold-base-media.py
system/dev/scripts/wipe_dev.py
ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Whiteboard.vue

Issue 806 Largest paintbrush

---

studio/media.py
ui/studio/src/components/media/MediaForm/MediaPermissions.vue
ui/studio/src/components/media/MediaForm/composable.ts
ui/studio/src/components/media/MediaForm/index.vue
ui/studio/src/models/studio.ts

Issue 859 Notes area in media permission

---

ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

Issue 876 Filter email recipients and consistence sort order

---

mail/mail_utils.py
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

I just realized that the email notification system hadn't been working for a while, because of missing `EMAIL_PORT` inside config. And I'm submitting some code change to make the BCC works.
Resolves #875, #819

Issue 875 Emails not sending

---

mail/templates.py

Fix typo & update email template in #875

Issue 875 Update email template

---

ui/dashboard/src/components/RTMPStream.vue
ui/dashboard/src/components/objects/Streamer/composable.js
ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/components/stage/Toolbox/tools/Streams/index.vue
ui/dashboard/src/services/rest/nms.js

Issue 738 Stream replays

---

ui/dashboard/src/views/backstage/StageManagement/General.vue

Resolves #810 
We also need to fallback stage status for these stages that was created before this PR and not having any status. I will do that after this PR got merged 👌

Issue 810 Default stage status

---

ui/dashboard/src/views/backstage/Admin/SystemConfiguration.vue

This is a patch for fixing an impact after implement issue #882

Issue 882 Consistence config after saving

---

stage/schema.py
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/store/modules/cache.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue

Issue 873 Stage visibility on Foyer

---

ui/dashboard/src/views/backstage/StageManagement/General.vue

Issue 901 Hide from stage list button

---

ui/dashboard/package.json
ui/dashboard/src/components/stage/Entry.vue
ui/dashboard/src/views/Home.vue
ui/dashboard/yarn.lock

Issue 897 Masonry grid

---

auth/auth_api.py

I just realized that `user1` on `dev-app1` couldn't be able to login, not because of incorrect password but because the user has role of `Super Admin`, and that role requires TOTP to authenticate. I don't think OTP is necessary in our project because it would make the project setup and authentication more complicated than necessary!

Fix login stuck of Super Admin role

---

mail/mail_utils.py
mail/templates.py
studio/media.py

Issue 790 Studio permission system email notification

---

studio/media.py
ui/dashboard/src/views/backstage/Layout.vue

Issue 871 Guest should not have access to Studio

---

system/dev/scripts/scaffold-base-media.py

Update user creation, foyer and system settings in the scaffolding script. Resolves #898

Issue 898 Base configuration

---

ui/dashboard/src/views/backstage/Admin/DeleteUser.vue
user/schema.py

Issue 918 Deleting player

---

README.md

Issue 927 Stage offline on Firefox

---

config/schema.py
mail/mail_utils.py
ui/dashboard/src/services/graphql/config.js
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

Issue 810 Options to send as BCC

---

ui/dashboard/src/i18n/vn.js
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

Allow email to be sent without specified "To" (only BCC). Close #819

Issue 819 No required to field

---

studio/media.py
ui/dashboard/src/components/objects/Object.vue
ui/dashboard/src/i18n/en.js
ui/dashboard/src/i18n/vn.js
ui/studio/src/components/media/MediaForm/PropLink.vue
ui/studio/src/components/media/MediaForm/index.vue
ui/studio/src/models/studio.ts

Issue 940 Optional hover effect in prop link

---

ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
ui/dashboard/src/components/objects/Meeting/Jitsi.vue
ui/dashboard/src/components/objects/Streamer/index.vue

Issue 944 Individual mode context menu

---

mail/templates.py
ui/dashboard/src/components/form/Field.vue
ui/dashboard/src/services/graphql/user.js
ui/dashboard/src/views/Register.vue
ui/dashboard/src/views/backstage/Admin/UserTable.vue
ui/dashboard/src/views/backstage/Layout.vue
user/models.py
user/schema.py
user/sqlfiles/create.sql

Issue 945 Required introduction

---

config/schema.py
ui/dashboard/src/components/NavBar.vue
ui/dashboard/src/i18n/en.js
ui/dashboard/src/i18n/vn.js
ui/dashboard/src/services/graphql/config.js
ui/dashboard/src/views/backstage/Admin/FoyerCustomisation.vue

Issue 946 Registration button visibility

---

ui/dashboard/src/views/backstage/StageManagement/General.vue

Issue 947 Stage owner and permission

---

ui/dashboard/src/components/objects/Streamer/index.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue
ui/dashboard/src/i18n/en.js
ui/dashboard/src/i18n/vn.js

Issue 890 Offline video context menu

---

ui/dashboard/src/components/ContextMenu.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scenes/Scene.vue

Issue 961 Scene switching on context menu open

---

.github/workflows/playwright-dev.yml
README.md
stage/schema.py
ui/dashboard/package.json
ui/dashboard/src/store/modules/cache.js
ui/dashboard/src/views/backstage/StageManagement/General.vue
ui/dashboard/src/views/backstage/StageManagement/index.vue

Issue 967 Stage visibility

---

ui/dashboard/src/components/objects/Streamer/index.vue

Issue 974 Stop removing stream automatically on disconnect

---

ui/dashboard/src/components/objects/Meeting/index.vue
ui/dashboard/src/components/stage/Toolbox/Skeleton.vue

Fix issue https://github.com/upstage-org/upstage/issues/836

place avatar on top jitsi window

---

ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

Resolve https://github.com/upstage-org/upstage/issues/966

Change message noti when sendding email

---

ui/dashboard/src/components/LanguageSelector.vue

Resolve https://github.com/upstage-org/upstage/issues/977

change american flag to british flag

---

ui/dashboard/src/components/objects/Meeting/index.vue

Resolve problem resizing avatar when it's on the op of jitsi window (https://github.com/upstage-org/upstage/issues/836)

resize avatar on top jitsi window

---

ui/studio/src/components/media/MediaFilter.vue

Resolve https://github.com/upstage-org/upstage/issues/987

Remove Shape, Media, Stream out of media list filter

---

ui/studio/src/components/media/MediaFilter.vue
ui/studio/src/components/media/MediaForm/index.vue

Resolve https://github.com/upstage-org/upstage/issues/986 and https://github.com/upstage-org/upstage/issues/987

Remove Stream in edit, add Stream in filter, remove Media in upload

---

ui/dashboard/package.json
ui/dashboard/yarn.lock

Dependeabot Security updates merged into main need to be brought over.

Dependeabot Security updates.

---

ui/dashboard/src/App.vue
ui/dashboard/src/components/LoginForm.vue

Resolve https://github.com/upstage-org/upstage/issues/1014

Fetch Stages after login

---

ui/dashboard/src/components/stage/Chat/ClearChat.vue
ui/dashboard/src/components/stage/Chat/PlayerChat.vue
ui/dashboard/src/components/stage/Chat/index.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/views/backstage/StageManagement/ClearChat.vue

-Clear chat in stage management can't clear player chat: fixed
-Make clear chat button on action bar in player chat and public chat : (Just for editor and owner)

Fix clear chat in manager , create clearchat function on stage

---

ui/dashboard/src/components/stage/Chat/Messages.vue
ui/dashboard/src/i18n/en.js
ui/dashboard/src/i18n/vn.js
ui/dashboard/src/views/backstage/StageManagement/Archive.vue

Make separate chat log:
+make separate part of download and review chat in session list 
+make 2 separate button download all chat for audience and player chat
Make timestamp and change format of file name

Make separate chat log and make timestamp for file name

---

ui/dashboard/src/components/MultiTransferAccessColumn.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue

Make owner name showing in edit and access column on Genaral infomation  (Stage management) (It can't move to other column)

Make owner tag name in access column

---

ui/dashboard/src/components/MultiTransferAccessColumn.vue
ui/dashboard/src/views/backstage/StageManagement/General.vue

Make owner label in label and edit access column in Genaral Information

Make owner display name in player and edit access column

---

ui/dashboard/src/components/stage/SettingPopup/settings/SaveScene.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scenes/BlankScene.vue
ui/dashboard/src/components/stage/Toolbox/tools/Scenes/Scene.vue
ui/dashboard/src/store/modules/stage/index.js
ui/dashboard/src/store/modules/stage/reusable.js

- Make audio can be save in scenes option
- Fix bug blank scenes can't stop audio
- Fix bug audio time display in audio play tool when using blank scenes

Make audio in scenes

---

ui/dashboard/src/services/graphql/composable.js
ui/dashboard/src/utils/notification.js
ui/dashboard/src/views/backstage/Admin/EmailNotification.vue

- Make email notification (success and error) alway display until we close it by X button. (Does not affect other Upstage notificationn )
- Some kind of reset form when send mail success.

Adjust email notification display time

---

ui/dashboard/src/components/DataTable/index.vue
ui/dashboard/src/views/backstage/Admin/SwitchRole.vue
ui/dashboard/src/views/backstage/Admin/UploadLimit.vue

drop menu in the last 2 items will be displayed above (Role and Upload Limit)

Fixed the display of dropmenu at the bottom of the users table

---

ui/dashboard/src/utils/constants.js
ui/dashboard/src/views/Home.vue

Make order of stage can:
-  filter by search keyword
- sort stages by newest , latest , name

Make order of stage on foyer page

---

ui/dashboard/src/components/MultiSelectList.vue
ui/dashboard/src/services/graphql/stage.js
ui/dashboard/src/views/Home.vue
ui/dashboard/src/views/backstage/StageManagement/Media.vue

- Display total file size of selected media (Media in stage management)
- Remove filter of foyer pages

Display total file size of stage media

---

ui/dashboard/src/components/MultiTransferColumn.vue

Make the email address table completely clear after sending mail

make the email address table completely clear after sending mail

---

ui/dashboard/src/router/index.js

Issue 1068 Non-blocking blank dashboard

---

dashboard/src/views/backstage/StageManagement/index.vue
studio/src/components/stage/StageTable.vue

I forgot that we also have another entrance to the live stage from stage management. This is a continuation of #1106

Issue 1097 Open stages in new tab (cont.)

---

core/studio/schema.py
studio/src/components/Authorized.vue
studio/src/components/display/DDate.vue
studio/src/components/display/DName.vue
studio/src/components/display/DSize.vue
studio/src/components/stage/StageTable.vue
studio/src/utils/common.ts

Issue 1093 Stage table actions

---

studio/src/App.vue
studio/src/components/Footer.vue
studio/src/components/Layout.vue
studio/src/components/Sidebar.vue
studio/src/utils/common.ts

Issue 1082 Remove frame layout

---

scripts/devtools/scaffold-base-media.py
scripts/devtools/terminal_colors.py
scripts/devtools/wipe_dev.py

Issue 1101 Demo stage setup

---

README.md
scripts/devtools/scaffold-base-media.py
studio/src/components/media/MediaTable.vue

Issue 1097 Consistent open stage behavior

---

core/studio/schema.py
core/studio/tests/__init__.py
core/studio/tests/test_last_login.py
core/studio/tests/test_update_user.py
core/studio/user.py
core/user/test_email_update.py
dashboard/src/i18n/en.js
studio/src/App.vue
studio/src/components/Sidebar.vue
studio/src/components/display/DDate.vue
studio/src/models/fragment.ts
studio/src/views/admin/player-management/ChangePassword.vue
studio/src/views/admin/player-management/DeletePlayer.vue
studio/src/views/admin/player-management/PlayerForm.vue
studio/src/views/admin/player-management/PlayerTable.vue

- Finish Player management layout enhancement. Resolve #1011

UpStage Studio V1.5.1

---

dashboard/src/components/Logo.vue
dashboard/src/views/live/Layout.vue

Issue 1121 Navigate to studio from live stage

---

dashboard/src/i18n/de.js
dashboard/src/i18n/en.js
dashboard/src/i18n/vn.js
studio/src/components/Dropzone.vue
studio/src/components/LanguageSelector.vue
studio/src/components/Navbar.vue
studio/src/components/StudioVersion.vue
studio/src/views/admin/player-management/PlayerTable.vue

Issue 1130 Upload limit

---

studio/src/components/Dropzone.vue
studio/src/components/Navbar.vue

Issue 1132 Dismiss messages on click

---

dashboard/src/components/LoginForm.vue
dashboard/src/i18n/index.js
studio/src/i18n.ts

Issue 1018 Default locale

---

dashboard/src/components/LoginForm.vue
studio/src/components/stage/StageFilter.vue

Issue 1115 Default stage list

---

core/studio/schema.py
core/studio/user.py
dashboard/src/i18n/en.js
dashboard/src/router/index.js
dashboard/src/views/backstage/Admin/index.vue
studio/package.json
studio/src/components/Header.vue
studio/src/components/Sidebar.vue
studio/src/i18n.ts
studio/src/views/admin/batch-player-creation/index.vue
studio/src/views/admin/player-management/PlayerFilter.vue
studio/yarn.lock

- Create user panel, resolve #1140 #1139

UpStage Studio V1.5.2

---

studio/src/App.vue
studio/src/components/Confirm.vue
studio/src/components/Dropzone.vue
studio/src/components/media/MediaTable.vue
studio/src/components/stage/StageTable.vue
studio/src/utils/common.ts
studio/src/views/admin/batch-player-creation/index.vue
studio/src/views/admin/player-management/PlayerFilter.vue
studio/src/views/admin/player-management/PlayerForm.vue
studio/src/views/admin/player-management/PlayerTable.vue

Issue 1147 Role change in Studio

---

core/mail/templates.py

Issue 1167 Approval email wording

---

studio/src/components/Navbar.vue
studio/src/components/Sidebar.vue
studio/src/state/auth.ts
studio/src/views/admin/email-notifications/index.vue
studio/src/views/admin/player-management/PlayerForm.vue

Issue 1201 Profile link

---

dashboard/package.json
dashboard/pnpm-lock.yaml
dashboard/src/components/Modal.vue
dashboard/src/components/TermsOfService.vue

Issue 1180 Terms & Conditions

---

studio/package.json
studio/src/components/stage/StageTable.vue

Create New Stage & Manage Stage goes to old interface #1170

1170 goes oldinterface
